"""Filter the FICD wide table down to the ingredients the LP is allowed to use.

The pool lives in `config/ingredient_pool_africa.csv` (regenerated by
`scripts/build_ingredient_pool.py`). Each row carries flags for the fish-meal
cost-share cap (`is_fishmeal`) and binder cap (`is_binder`), an optional
per-ingredient `max_inclusion`, and a `countries` column listing the ISO-2 codes
where the ingredient is locally available. The `countries` tag is advisory only:
it drives the `locally_available` response flag and never restricts the LP.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path
from typing import Iterable, Optional

import pandas as pd

from .config.defaults import normalize_country
from .data_loader import load_ficd_wide

POOL_PATH = Path(__file__).parent / "config" / "ingredient_pool_africa.csv"


@dataclass(frozen=True)
class IngredientRecord:
    code: str
    description: str
    cls: str                         # informational grouping label; not used by the LP
    is_fishmeal: bool
    is_binder: bool
    max_inclusion: Optional[float]   # None ⇒ no per-ingredient cap
    countries: frozenset[str] = field(default_factory=frozenset)  # ISO-2 local-availability tags


def load_pool(only_codes: Optional[Iterable[str]] = None) -> list[IngredientRecord]:
    """Return the active ingredient pool, optionally restricted to `only_codes`.

    `only_codes` is typically the set of ingredient codes the miller has
    a price for at request time; ingredients without prices are excluded.
    The CSV is parsed once and cached (the pool file is static at runtime).
    """
    full = _load_full_pool()
    if only_codes is None:
        return list(full)
    keep = set(map(str, only_codes))
    return [rec for rec in full if rec.code in keep]


@lru_cache(maxsize=1)
def _load_full_pool() -> tuple[IngredientRecord, ...]:
    """Parse the pool CSV once into immutable records (cached like `load_ficd_wide`)."""
    raw = pd.read_csv(POOL_PATH, comment="#", dtype={"code": str})
    raw = raw[raw["code"].notna()].copy()
    return tuple(
        IngredientRecord(
            code=str(r["code"]).strip(),
            description=str(r["description"]),
            cls=str(r["class"]),
            is_fishmeal=bool(int(r.get("is_fishmeal", 0) or 0)),
            is_binder=bool(int(r.get("is_binder", 0) or 0)),
            max_inclusion=(
                float(r["max_inclusion"]) if pd.notna(r.get("max_inclusion")) else None
            ),
            countries=_parse_countries(r.get("countries")),
        )
        for _, r in raw.iterrows()
    )


def _parse_countries(cell: object) -> frozenset[str]:
    """Parse a comma-separated ISO-2 country cell into a normalized frozenset.

    Blank / missing ⇒ empty set (ingredient not locally available anywhere tracked).
    """
    if pd.isna(cell):
        return frozenset()
    return frozenset(n for c in str(cell).split(",") if (n := normalize_country(c)))


def attach_ficd_rows(records: list[IngredientRecord]) -> pd.DataFrame:
    """Return a wide FICD frame (one row per pool ingredient) keyed by code."""
    ficd = load_ficd_wide()
    codes = [r.code for r in records]
    sub = ficd[ficd["code"].isin(codes)].copy()
    missing = set(codes) - set(sub["code"])
    if missing:
        raise ValueError(
            f"Pool references FICD codes not present in the ingredient database: "
            f"{sorted(missing)}"
        )
    return sub.set_index("code").reindex(codes).reset_index()
