"""Regenerate the country-tagged ingredient pool CSV.

Combines two static inputs into ``fasa_core/config/ingredient_pool_africa.csv``:

  1. ``scripts/data/countries_pool.csv``  — the per-country usable-ingredient list
     (``code;country``, ISO-3, one row per code/country pair) supplied by the FASA team.
  2. ``data/FICD_…csv``                   — ingredient composition DB; source of
     descriptions and the authority on which codes the LP can actually use.

Output pool rows = ``(countries ∩ FICD) ∪ EXTRA_IMPORT_CODES``. Codes present in the
country list but ABSENT from FICD have no nutrient coefficients and cannot enter the LP,
so they are excluded (the count and range are logged at build time).

Per-ingredient metadata is derived from the description: ``class`` (informational),
``is_fishmeal`` (1 only for "Fish meal ..."), and ``is_binder`` (1 for starch/flour/
cassava binders). ``is_fishmeal``/``is_binder`` feed only the opt-in, off-by-default
advisory caps. Country membership is emitted as a comma-separated ISO-2 ``countries``
column; an empty value means "not locally available in any tracked country".

Run from the repo root:
    python scripts/build_ingredient_pool.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))  # allow `import fasa_core` without installing the package

from fasa_core.config.defaults import (  # noqa: E402  (after sys.path bootstrap)
    DEFAULT_DATA_DIR,
    FICD_FILENAME,
    SUPPORTED_COUNTRIES,
)
from fasa_core.ingredient_pool import POOL_PATH  # noqa: E402

COUNTRIES_SRC = REPO_ROOT / "scripts" / "data" / "countries_pool.csv"
FICD_SRC = DEFAULT_DATA_DIR / FICD_FILENAME
POOL_OUT = POOL_PATH

ISO3_TO_ISO2 = {"KEN": "KE", "NGA": "NG", "ZMB": "ZM"}

# Import/non-local variants kept in the pool even though they are not tagged for any
# tracked country: millers buy them, and the LP must never be limited to local items.
# They are present in FICD and carry an empty `countries` tag in the output.
#   10073 Fish meal, mixed fish, Mauritania   31252 Soybean meal, USA
#   23002 Poultry by-product meal             31621 Wheat flour, Trigo 30, Indonesia
#   30410 Cottonseed meal, degossypoled
EXTRA_IMPORT_CODES = ("10073", "23002", "30410", "31252", "31621")

OUTPUT_COLUMNS = [
    "code", "description", "class",
    "is_fishmeal", "is_binder", "max_inclusion", "countries",
]

HEADER_COMMENT = """\
# FASA country-tagged ingredient pool (generated by scripts/build_ingredient_pool.py).
# DO NOT edit by hand — change the inputs under scripts/data/ then re-run the builder.
#
# Columns:
#   countries      comma-separated ISO-2 codes (KE/NG/ZM) where the ingredient is locally
#                  available; blank = not locally available in any tracked country (e.g.
#                  import-only variants). Used ONLY to flag `locally_available` in the API
#                  response — the LP is NEVER restricted to local ingredients.
#   is_binder /    auto-derived from the description (fishmeal=1 only for "Fish meal ...";
#   is_fishmeal    binder=1 for starch/flour/cassava binders). These feed only the opt-in,
#                  off-by-default advisory caps.
#   max_inclusion  blank = no per-ingredient cap (LP decides). Only toxin (TX*) and ASNS
#                  nutrient limits are fixed.
#
# Country-pool codes absent from FICD (no composition data) are excluded and cannot be
# formulated until FICD gains their rows.
"""

BINDER_KEYWORDS = ("starch", "wheat flour")
BINDER_CASSAVA_FORMS = ("flour", "meal", "chip", "tuber")

# Coarse, informational class labels (class is not used by the LP).
_CLASS_RULES = [
    (("fish meal", "shrimp", "blood meal", "meat and bone", "poultry", "feather",
      "hydrolysate", "krill", "squid"), "animal_protein"),
    (("black soldier fly", "larvae", "insect", "mealworm"), "insect_meal"),
    (("premix",), "premix"),
    (("l-lysine", "dl-methionine", "l-threonine", "l-tryptophan", "synthetic"), "synthetic_aa"),
    (("limestone", "phosphate", "salt", "calcium", "sodium", "magnesium",
      "mineral", "dcp", "mcp"), "mineral"),
    (("oil", "fat", "tallow", "lard", "lecithin"), "lipid"),
    (("yeast", "vitamin", "enzyme", "acid", "additive"), "functional"),
    (("starch", "cassava", "wheat flour", "potato"), "binder"),
    # Protein meals are matched BEFORE cereal by-products so oilseed *meals* described
    # as "dehulled"/"with hulls" aren't captured by the hull/husk by-product keywords.
    # Standalone "X hulls" (no "meal") still fall through to cereal_byproduct below.
    # `cottonseed meal` (not bare `cottonseed`) keeps "Cottonseed hulls" a by-product.
    (("soybean meal", "sunflower meal", "cottonseed meal", "groundnut", "peanut",
      "rapeseed", "canola", "gluten meal", "meal"), "protein_meal"),
    (("bran", "middling", "pollard", "hull", "husk", "gluten feed"), "cereal_byproduct"),
    (("corn", "maize", "sorghum", "wheat", "rice", "millet", "barley", "grain"), "cereal"),
]


def _classify(description: str) -> str:
    low = description.lower()
    for keywords, label in _CLASS_RULES:
        if any(k in low for k in keywords):
            return label
    return "unclassified"


def _derive_is_fishmeal(description: str) -> int:
    return int(description.strip().lower().startswith("fish meal"))


def _derive_is_binder(description: str) -> int:
    low = description.lower()
    if any(k in low for k in BINDER_KEYWORDS):
        return 1
    if "cassava" in low and any(f in low for f in BINDER_CASSAVA_FORMS):
        return 1
    return 0


def main() -> int:
    # The builder's ISO3→ISO2 map must be able to emit every API-supported country,
    # otherwise a country could be accepted by the API yet tag nothing in the pool.
    uncovered = set(SUPPORTED_COUNTRIES) - set(ISO3_TO_ISO2.values())
    if uncovered:
        raise SystemExit(f"ISO3_TO_ISO2 does not cover SUPPORTED_COUNTRIES: {sorted(uncovered)}")

    # ---- inputs ----
    countries = pd.read_csv(COUNTRIES_SRC, sep=";", dtype=str, encoding="utf-8-sig")
    countries["code"] = countries["code"].str.strip()
    countries["country"] = countries["country"].str.strip()

    ficd = pd.read_csv(FICD_SRC, dtype=str, encoding="utf-8-sig")
    ficd["code"] = ficd["code"].str.strip()
    ficd_desc = (
        ficd.dropna(subset=["code"])
        .drop_duplicates("code")
        .set_index("code")["description"]
    )
    ficd_codes = set(ficd_desc.index)

    # ISO-2 country membership per code
    membership: dict[str, set[str]] = {}
    for _, r in countries.iterrows():
        iso2 = ISO3_TO_ISO2.get(r["country"])
        if iso2:
            membership.setdefault(r["code"], set()).add(iso2)

    attached_codes = set(membership)
    excluded = sorted(attached_codes - ficd_codes, key=lambda c: int(c) if c.isdigit() else c)

    missing_imports = [c for c in EXTRA_IMPORT_CODES if c not in ficd_codes]
    if missing_imports:
        raise SystemExit(f"EXTRA_IMPORT_CODES absent from FICD: {missing_imports}")

    # pool = (country codes present in FICD) ∪ (retained import variants)
    pool_codes = sorted(
        (attached_codes & ficd_codes) | set(EXTRA_IMPORT_CODES),
        key=lambda c: int(c) if c.isdigit() else c,
    )

    rows = []
    for code in pool_codes:
        description = ficd_desc.get(code, "")
        rows.append({
            "code": code,
            "description": description,
            "class": _classify(description),
            "is_fishmeal": _derive_is_fishmeal(description),
            "is_binder": _derive_is_binder(description),
            "max_inclusion": "",
            "countries": ",".join(sorted(membership.get(code, set()))),
        })

    out = pd.DataFrame(rows, columns=OUTPUT_COLUMNS)
    out = out.sort_values(["class", "code"], kind="stable").reset_index(drop=True)

    POOL_OUT.parent.mkdir(parents=True, exist_ok=True)
    with POOL_OUT.open("w", encoding="utf-8", newline="") as fh:
        fh.write(HEADER_COMMENT)
        out.to_csv(fh, index=False)

    # ---- summary ----
    # The is_fishmeal/is_binder lists are printed in full so a human can audit the
    # heuristic on every regeneration (these flags feed the opt-in advisory caps).
    fishmeal_codes = out.loc[out["is_fishmeal"] == 1, "code"].tolist()
    binder_codes = out.loc[out["is_binder"] == 1, "code"].tolist()
    print(f"wrote {POOL_OUT.relative_to(REPO_ROOT)}: {len(out)} rows")
    print(f"  is_fishmeal=1 ({len(fishmeal_codes)}): {', '.join(fishmeal_codes)}")
    print(f"  is_binder=1   ({len(binder_codes)}): {', '.join(binder_codes)}")
    print(f"  retained import variants (empty countries): {len(EXTRA_IMPORT_CODES)}")
    print(f"  country-pool codes EXCLUDED (absent from FICD): {len(excluded)}")
    if excluded:
        print(f"    range: {excluded[0]}..{excluded[-1]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
